name: Main Workflow



on:
  push:
    branches:
      - main
    paths:
      - 'src/**/*'
      - '.github/**/*'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
jobs:
  RunUnitTest:
    uses: './.github/workflows/unit-test.yaml'
  RunIntegrationTest:
    uses: './.github/workflows/integration-test.yaml'
    needs: RunUnitTest
  RunSonarScan:
    uses: './.github/workflows/sonar-scan.yaml'
    needs: RunIntegrationTest
    secrets:
      SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
  Build:
    uses: './.github/workflows/build.yaml'
#    needs: RunSonarScan
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: us-east-1
